import { useState, type FormEvent } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Mail, MapPin, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageBanner } from "@/components/site-shell";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [{ title: "Contact Meridian Workforce" }, { name: "description", content: "Speak with Meridian Workforce about hiring, talent placement, and international workforce support." }, { property: "og:title", content: "Contact Meridian Workforce" }, { property: "og:description", content: "Tell us what your team needs next." }] }), component: ContactPage });

function ContactPage() { const [sent, setSent] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); }; return <><PageBanner eyebrow="Contact us" title="Tell us what your team needs next." description="Whether you are hiring one specialist or building an entire workforce, our team is ready to listen." /><section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.05fr_0.95fr] lg:px-8"><form onSubmit={submit} className="glass-panel rounded-2xl p-7 sm:p-9"><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" required /><Field label="Email" name="email" type="email" required /><Field label="Phone" name="phone" required /><Field label="Subject" name="subject" required /></div><label className="mt-5 block text-sm text-muted-foreground">Message<textarea name="message" required rows={6} className="mt-2 w-full resize-none rounded-lg border border-input bg-background/50 px-4 py-3 text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" /></label><div className="mt-6 flex flex-wrap items-center gap-4"><Button type="submit" className="rounded-full px-6">{sent ? "Message received" : "Send enquiry"}</Button>{sent && <span className="text-sm text-teal">Thanks — our team will be in touch shortly.</span>}</div></form><div><p className="eyebrow text-teal">Find us</p><h2 className="mt-3 font-display text-3xl font-bold">A conversation starts here.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Our Dubai team is available Sunday to Thursday, 9:00 am to 6:00 pm GST.</p><div className="mt-8 space-y-5 text-sm text-muted-foreground"><div className="flex gap-3"><MapPin className="size-5 shrink-0 text-primary" /><span>Marina Tower, Dubai<br />United Arab Emirates</span></div><div className="flex gap-3"><Phone className="size-5 shrink-0 text-primary" /><span>+971 4 555 0142</span></div><div className="flex gap-3"><Mail className="size-5 shrink-0 text-primary" /><span>hello@meridianworkforce.com</span></div></div><div className="mt-10 flex min-h-56 items-end rounded-2xl border border-line bg-accent/60 p-6"><div><p className="eyebrow text-primary">Dubai · UAE</p><p className="mt-2 text-sm text-muted-foreground">A central base for a global workforce.</p></div></div></div></section></>; }

function Field({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <label className="block text-sm text-muted-foreground">{label}<input name={name} type={type} required={required} className="mt-2 h-11 w-full rounded-lg border border-input bg-background/50 px-4 text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" /></label>; }