import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, FileCheck2, SearchCheck, ShieldCheck, UserRoundCheck } from "lucide-react";
import { PageBanner, PrimaryLink, SectionIntro } from "@/components/site-shell";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [{ title: "HR & Recruitment Services | Skillmint" }, { name: "description", content: "Explore Skillmint's talent acquisition, workforce solutions, candidate assessment, and strategic industry partnerships." }, { property: "og:title", content: "HR & Recruitment Services | Skillmint" }, { property: "og:description", content: "Flexible and dependable talent solutions for every stage of growth." }] }), component: ServicesPage });

const services = [
  { icon: SearchCheck, title: "Talent Acquisition & Recruitment", description: "End-to-end sourcing and hiring support across industries and role levels.", items: ["Requirement understanding", "Targeted sourcing", "Candidate shortlisting", "Interview coordination"] },
  { icon: FileCheck2, title: "HR & Workforce Solutions", description: "Strategic, cost-efficient HR management support, consultancy, and workforce planning for growing businesses.", items: ["Workforce planning", "HR consultancy", "Onboarding support", "People operations"] },
  { icon: ShieldCheck, title: "Candidate Screening & Assessment", description: "In-depth evaluation of experience, skills, and job fit to identify the ideal talent match for each role.", items: ["Profile evaluation", "Experience checks", "Communication assessment", "Job-fit review"] },
  { icon: UserRoundCheck, title: "Strategic Industry Partnerships", description: "Long-term recruitment partnerships built around each client's workforce challenges and business objectives.", items: ["Single-role hiring", "Large-scale hiring", "Flexible engagement", "Ongoing support"] },
];

function ServicesPage() { return <><PageBanner eyebrow="Our services" title="Talent solutions built around your needs." description="Whether you need to fill a single position or manage large-scale hiring, we offer flexible and dependable talent solutions." /><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-4 lg:grid-cols-2">{services.map(({ icon: Icon, title, description, items }, index) => <article key={title} className="glass-panel rounded-2xl p-7 transition-transform hover:-translate-y-1 sm:p-9"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-xl bg-secondary/15 text-primary"><Icon /></span><span className="font-mono text-xs text-teal">0{index + 1}</span></div><h2 className="mt-10 font-display text-2xl font-bold">{title}</h2><p className="mt-3 max-w-lg leading-relaxed text-muted-foreground">{description}</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className="flex items-center gap-2 text-sm text-muted-foreground"><ArrowRight className="size-4 text-secondary" />{item}</li>)}</ul></article>)}</div></section><section className="border-y border-line bg-accent/40"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionIntro eyebrow="Our promise" title="A process you can trust." description="We combine thoughtful assessment, clear communication, and dedicated support from the first brief to the final selection." /><div className="mt-10"><PrimaryLink to="/process">See our recruitment process</PrimaryLink></div></div></section></>; }